# Generated by Django 4.1.5 on 2023-01-22 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='registered_vehicle_owner_table',
            fields=[
                ('registered_vehicle_owner', models.CharField(max_length=30)),
                ('registered_owner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registered_owner_address', models.CharField(max_length=160)),
                ('registered_owner_dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_license_plate_registration_table',
            fields=[
                ('city_name', models.CharField(max_length=30)),
                ('vehicle_classification', models.CharField(max_length=10)),
                ('vin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('engine_cc', models.IntegerField()),
                ('vehicle_brand', models.CharField(max_length=30)),
                ('registered_owner_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='myapp.registered_vehicle_owner_table')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Police', 'Police'), ('BRTA_Staff', 'BRTA_Staff')], max_length=20)),
                ('designation', models.CharField(blank=True, max_length=60, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
