# Generated by Django 4.1.5 on 2023-01-23 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_vehicle_owner_table',
            name='registered_owner_data_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle_license_plate_registration_table',
            name='registered_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registered_vehicle_owner_table'),
        ),
    ]
