# Generated by Django 4.1.5 on 2023-01-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_registered_vehicle_owner_table_registered_owner_data_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_vehicle_owner_table',
            name='registered_owner_data_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
