# Generated by Django 4.1.5 on 2023-01-26 16:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_registered_vehicle_owner_table_registered_owner_data_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Felony_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('felony_name', models.CharField(max_length=60)),
                ('felony_fine', models.IntegerField()),
                ('frlony_details', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleOwnerFelonyIncident',
            fields=[
                ('incident_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_title', models.CharField(max_length=100)),
                ('incident_location', models.CharField(max_length=100)),
                ('incident_details', models.CharField(max_length=300)),
                ('incident_submitted_by', models.CharField(max_length=60)),
                ('incident_charges', models.ManyToManyField(to='myapp.felony_list')),
                ('registered_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registered_vehicle_owner_table')),
            ],
        ),
    ]
