# Generated by Django 4.1.5 on 2023-01-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_felony_list_vehicleownerfelonyincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleownerfelonyincident',
            name='incident_submitted_by',
            field=models.CharField(editable=False, max_length=60),
        ),
    ]
