# Generated by Django 4.1.5 on 2023-01-26 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_vehicleownerfelonyincident_incident_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleownerfelonyincident',
            name='incident_submition_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
