# Generated by Django 4.1.5 on 2023-01-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_userprofile_user_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleownerfelonyincident',
            name='incident_charges',
        ),
        migrations.RemoveField(
            model_name='vehicleownerfelonyincident',
            name='registered_owner_id',
        ),
        migrations.DeleteModel(
            name='Felony_List',
        ),
        migrations.DeleteModel(
            name='VehicleOwnerFelonyIncident',
        ),
    ]
