# Generated by Django 4.1.5 on 2023-02-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_felonylist_incidentvehicular'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_vehicle_owner_table',
            name='registered_owner_email',
            field=models.EmailField(default='smarifmahmud9@gmail.com', max_length=255),
        ),
    ]
