# Generated by Django 4.1.5 on 2023-02-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_registered_vehicle_owner_table_registered_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_vehicle_owner_table',
            name='registered_owner_email',
            field=models.EmailField(max_length=255),
        ),
    ]
